version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8555:80"
    depends_on:
      - app

    container_name: parsing_nginx

  app:
    build:
        context: .
        dockerfile: _docker/app/DockerFile
    volumes:
      - ./:/var/www
    depends_on:
        - db
    container_name: parsing_app
  db:
    image: mysql:8.0
    restart: always
    volumes:
        - ./tmp/db:/var/lib/mysql
    environment:
        MYSQL_DATABASE: parsing
        MYSQL_ROOT_PASSWORD: root
    ports:
        - 8766:3306
    command:
        --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: parsing_db

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
          - 8080:80
      environment:
          PMA_ARBITRARY: 1
          PMA_HOST: db
          PMA_USER: root
          PMA_PASSWORD: root
      depends_on:
          - db
